[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
optimizer_runs = 1_000_000
remappings = [
    'transmissions11/solmate/=lib/solmate/',
    'forge-std/=lib/forge-std/src/',
    'solady/=lib/solady/',
]


[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_KEY}" }
