[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
optimizer_runs = 1_000_000
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solady/=lib/solady/',
    'solmate/=lib/solmate/src',
]


[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"
base_goreli = "${RPC_URL_BASE_GOERLI"
base_mainnet = "${RPC_URL_BASE_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
base_mainnet = {key = "${BASESCAN_KEY}"}