[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
optimizer_runs = 1_000_000
via_ir = true
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solady/=lib/solady/src/',
    'solmate/=lib/solmate/src/',
]
libraries = [
    "src/utils/Perlin.sol:Perlin:0x5499e963931d359553380bCA52077ecB0E2419d6",
    "src/utils/metadata/KingArt.sol:KingArt:0xcD1842728b73611445c87801889CAE24CF5502c6",
    "src/utils/metadata/ParArt.sol:ParArt:0xBc475ce743B5C331A62d55Ce19A83De47d978e1C"
]


[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
base_goerli = "${RPC_URL_BASE_GOERLI"
base_mainnet = "${RPC_URL_BASE_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
base_goerli = {key = "${BASESCAN_KEY}", url = "https://api-goerli.basescan.org/api"}
base_mainnet = {key = "${BASESCAN_KEY}", url = "https://api-mainnet.basescan.org/api"}
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}